const APPConfig = {
  // API_URL: "http://54.162.2.199:5001/api",
  // API_URL: "http://10.179.25.131:5001/api",
  // API_URL: "http://34.69.85.115:5000/api",
  API_URL: "http://13.60.148.152:5000/api"
  // API_URL: "http://13.202.131.63:5000/api"
};

const ApiEndPoints = {
  Login: `${APPConfig.API_URL}/auth/login`,
  TenantAddUpdate: `${APPConfig.API_URL}/master/add-update-tenant`,
  MasterList: `${APPConfig.API_URL}/master/list`,
  ConectoreList: `${APPConfig.API_URL}/connector/connector-list`,
  TenantList: `${APPConfig.API_URL}/tenant/user-list`,
  UserAddUpdate: `${APPConfig.API_URL}/tenant/add-update-user`,
  UserDelete: `${APPConfig.API_URL}/tenant/delete-user`,
  InstallConnector: `${APPConfig.API_URL}/upload-connector`,
  InsertMultiConnector: `${APPConfig.API_URL}/connector/insert-multi-connector`,
  AsynConnector: `${APPConfig.API_URL}/connector/share-connector`,
  ActiveConnector: `${APPConfig.API_URL}/connector/activate-connector`,
  AsynConnectorUser: `${APPConfig.API_URL}/connector/shareConnectorToUser`,
  UserCreateDashboard: `${APPConfig.API_URL}/dashboard/create-dashboard`,
  UserDashbordList: `${APPConfig.API_URL}/dashboard/get-dashboard`,
  UserConnnectorList: `${APPConfig.API_URL}/connector/connectorListForUser`,
  // ConnecterDelete: `${APPConfig.API_URL}/connector/delete-connectorByMaster`,
  ConnecterDelete: `${APPConfig.API_URL}/connector/delete-connector`,
  ConnecterDeleteTenant: `${APPConfig.API_URL}/connector/delete-connectorByTenant`,
  // RunScheduler: `${APPConfig.API_URL1}/data`,
  ElasticData: `${APPConfig.API_URL}/elastic/data/`,
  GetDashboardData: `${APPConfig.API_URL}/dashboard/get-dashborad-data`,
  DeleteData: `${APPConfig.API_URL}/dashboard/delete-dashborad-data`,
  AddDashboardData: `${APPConfig.API_URL}/dashboard/add-dashborad-data`,
  CreateReport: `${APPConfig.API_URL}/report/create-report`,
  GetReportList: `${APPConfig.API_URL}/report/get-report`,
  AddReportData: `${APPConfig.API_URL}/report/add-report-data`,
  UpdateReportData: `${APPConfig.API_URL}/report/edit-report-data`,
  GetReportData: `${APPConfig.API_URL}/report/get-report-data`,
  DeleteReportData: `${APPConfig.API_URL}/report/delete-report-data`,
  DeleteDashboard: `${APPConfig.API_URL}/dashboard/delete-dashboard`,
  DeleteReport: `${APPConfig.API_URL}/report/delete-report`,
  UpdateDashboard: `${APPConfig.API_URL}/dashboard/update-dashboard`,
  UpdateDashboardTitle: `${APPConfig.API_URL}/dashboard/update-table-title`,
  UpdateReport: `${APPConfig.API_URL}/report/update-report`,
  UpdateReportTitle: `${APPConfig.API_URL}/report/update-reportTable-title`,
  CVESearch: `${APPConfig.API_URL}/elastic/cveSearch`,
  EmailScheduler: `${APPConfig.API_URL}/schedule/email-report`,
  ConnectorInsert: `${APPConfig.API_URL}/connector/insert-multi-connector`,
  UploadConnector: `${APPConfig.API_URL}/upload-connector?`,
  MurgeReort: `${APPConfig.API_URL}/report/merge-report`,
  ConnectorConfig: `${APPConfig.API_URL}/connector/add-connector-config`,
  ConnectorScheduler: `${APPConfig.API_URL}/connector/schedule`,
  ConnectorLog: `${APPConfig.API_URL}/connector/connector-log`,
  ConnectorConfigDetail: `${APPConfig.API_URL}/connector/connector-config-detail`,
  DSMList: `${APPConfig.API_URL}/elastic/dsmlist`,
  HostCompilanceData: `${APPConfig.API_URL}/elastic/hostCompilance`,
  CSVCompilanceData: `${APPConfig.API_URL}/elastic/cveReport`,
  ElasticIndexList: `${APPConfig.API_URL}/elastic/dataSource`,
  DeleteIndex: `${APPConfig.API_URL}/elastic/data/index`,
  SearchData: `${APPConfig.API_URL}/elastic/data/search`,
  ConnectorParameterSave: `${APPConfig.API_URL}/connector/connector-parameter-save`,
  UploadFileData: `${APPConfig.API_URL}/document/upload-document`,
  FileList: `${APPConfig.API_URL}/document/document-list`,
  FileGet: `${APPConfig.API_URL}/document/get-document`,
  FileDelete: `${APPConfig.API_URL}/document/delete-document`,
  ConformityChecks: `${APPConfig.API_URL}/elastic/conformity-new-checks`,
  ContainerRuntimeSensor: `${APPConfig.API_URL}/elastic/container-runtime-sensor`,
  ContainerEvaluation: `${APPConfig.API_URL}/elastic/container-evaluation`,
  ContainerRuntimeVulnerabilityView: `${APPConfig.API_URL}/elastic/container-runtime-vulnerability-view`,
  SmartScanDetail: `${APPConfig.API_URL}/elastic/smart-scan-detail`,
  RegistriesList: `${APPConfig.API_URL}/elastic/smart-check-registries-list`,
  ChangeLanguage : `${APPConfig.API_URL}/connector/change-language`,
};

export default ApiEndPoints;
